apiVersion: apps/v1
kind: Deployment
metadata:
  name: call-forecast-backend
  namespace: mlops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: call-forecast-backend
  template:
    metadata:
      labels:
        app: call-forecast-backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8000"
    spec:
      containers:
        - name: backend
          image: ghcr.io/jamik-ai/mlops-course-incident-classifier:b7cab9bdf5f53a9eed8abfd605349d5ccfcfb1eb
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: PYTHONPATH
              value: /app
            - name: MLFLOW_TRACKING_URI
              value: http://mlflow:5000
            - name: MLFLOW_MODEL_NAME
              value: call-volume-forecast
            - name: AWS_ENDPOINT_URL
              value: http://minio:9000
            - name: AWS_ACCESS_KEY_ID
              value: minioadmin
            - name: AWS_SECRET_ACCESS_KEY
              value: minioadmin
            - name: MLFLOW_DEFAULT_ARTIFACT_ROOT
              value: s3://mlflow
          volumeMounts:
            - name: app-data
              mountPath: /app/data
            - name: app-models
              mountPath: /app/models
            - name: app-reports
              mountPath: /app/reports
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 20
      volumes:
        - name: app-data
          persistentVolumeClaim:
            claimName: app-data-pvc
        - name: app-models
          persistentVolumeClaim:
            claimName: app-models-pvc
        - name: app-reports
          persistentVolumeClaim:
            claimName: app-reports-pvc
