apiVersion: apps/v1
kind: Deployment
metadata:
  name: call-forecast-frontend
  namespace: mlops
  annotations:
    argocd-image-updater.argoproj.io/frontend.image-name: ghcr.io/jamik-ai/mlops-course-incident-classifier-frontend
    argocd-image-updater.argoproj.io/frontend.update-strategy: latest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: call-forecast-frontend
  template:
    metadata:
      labels:
        app: call-forecast-frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/jamik-ai/mlops-course-incident-classifier-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
