apiVersion: v1
kind: Service
metadata:
  name: call-forecast-frontend
  namespace: mlops
spec:
  selector:
    app: call-forecast-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: NodePort
