apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: mlops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
        - name: mlflow
          image: ghcr.io/jamik-ai/mlops-course-incident-classifier-mlflow:latest
          imagePullPolicy: Always
          command: ["/bin/sh", "-c"]
          args: ["mlflow server --backend-store-uri 'sqlite:////tmp/mlflow/mlflow.db' --default-artifact-root '/tmp/mlflow/artifacts' --host 0.0.0.0 --port 5000"]
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: mlflow-artifacts
              mountPath: /tmp/mlflow/artifacts
      volumes:
        - name: mlflow-artifacts
          persistentVolumeClaim:
            claimName: mlflow-artifacts-pvc
